apiVersion: v1
kind: Namespace
metadata:
  name: application-sample
---
apiVersion: application.sample.ibm.com/v1alpha1
kind: Application
metadata:
  name: application1
  namespace: application-sample
spec:
  version: "1.0.0"
  amountPods: 2
  databaseName: database
  databaseNamespace: database
